const Psych=[
    {
        id: 1,
        img:"https://cdn.thelivelovelaughfoundation.org/the_live_love_laugh/uploads/media/source/znbtnT-CB62FB35-31D8-432A-B035-26F373BBFF0B---Aaisha-Khan-1.png",
        name:"Aaisha Khan",
        email:"aaishadotkhan@gmail.com",
        ph:"9769296832",
        sp:"Relationship Counselling, Depression, Anxiety, Personality Disorders, Adolescent Issues, Marital Therapy.",
    },
    {
        id: 2,
        img:"Aakanksha-Kanojia.jpg",
        name:"Aakanksha Kanojia",
        email:"aakanksha@hopealive.in",
        ph:"9716765236",
        sp:"Trauma informed, Queer Affirmative, Mindfulness based Specialist",
    },
    {
        id: 3,
        img:"xfqRXe-Aakhansha-Varghese.jpg",
        name:"Aakriti Varghese",
        email:"aakriti151995@gmail.com",
        ph:"9986071608",
        sp:"Relationships, Anxiety, Depression, Trauma, Life events, Couples and Family therapy, Deaddiction, LGBTQIA- Affirmative Practitioner",
    },
    {
        id: 4 ,
        img:"mnDYQV-Avantika-M---Avantika-Malhautra.jpg",
        name:"Avantika Malhautra",
        email:"anamika.bt@gtmail.com",
        ph:"9898723456",
        sp:"Anxiety, Depression, Stress, Addiction, Anger, Bipolar Disorders, Grief",
    },
    {
        id: 5,
        img:"tGLvvj-L1---BADSHAH-KING.jpg",
        name:"Anshul Khosla",
        email:"support@amahahealth.com",
        ph:"020 71171501",
        sp:"Problematic Smartphone Use, Pain Management, Mindfulness In Daily Life, Crisis Management, Personality Disorders",
    },
    {
        id: 6,
        img:"anand goud.jpg",
        name:"Anand Goud",
        email:"manourja@gmail.com",
        ph:"9406616978",
        sp:"Teenager and Youth Counseling, Pain Management, Crisis Management",
    },
    {
        id: 7,
        img:"sJwzXT-Neelu-Khanna.jpg",
        name:"Neelu Khanna",
        email:"support@amahahealth.com",
        ph:"020 71171501",
        sp:"Depression, Bipolar Disorder, and Anxiety Disorders such as Social Anxiety and Generalized Anxiety, Learning Disability",
    },
    {
        id: 8,
        img:"dJwUdf-Anuradha-Babu---IMPACKT-Original.jpg",
        name:"Aanuradha Babu",
        email:"impacktmind@gmail.com",
        ph:"6361631723",
        sp:"General Mental Wellness for all age groups, Career Guidance, Conducting Life Skills Sessions",
    },
    {
        id: 9,
        img:"mrigtrisha.jpg",
        name:"Mrigtrisha S",
        email:"mrigtrishna10@gmail.com",
        ph:"9782169011, 9945514264",
        sp:"Psychotherapy & Relational Psychotherapy, Bipolar Disorders, Schizophrenia",
    },
    {
        id: 10,
        img:"farah.png",
        name:"Farah Manekshaw",
        email:"farah.themirroredroom@gmail.com",
        ph:"7249560363",
        sp:"Works with Couples, Queer folks and Neurodivergent people with a trauma informed lens",
    },
    {
        id: 11,
        img:"gopika.jpg",
        name:"Gopica Anand",
        email:"gopica.ga@gmail.com",
        ph:"7702575202",
        sp:"Interpersonal, Work-place and Relationships Issues, Stress",
    },
    {
        id: 12,
        img:"jaikumar.png",
        name:"Jaikumar Velayudham",
        email:"maildrjai@rediffmail.com",
        ph:"9841707437, 9941241507",
        sp:"Adolescent Mental Wellbeing, Internet Addiction, Depression, Bipolar Disorder, Schizophrenia",
    },
];
export default Psych;